stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
    outs:
      - artifacts/DataIngestionArtifacts\raw_data.csv
      - artifacts/DataIngestionArtifacts\imb_data.csv