model:
  learning_rate: 0.01
  batch_size: 128
  epochs: 1
  optimizer: adam
  max_words: 50000
  max_len: 300
  loss: binary_crossentropy 
  activation: sigmoid
  metrics:
    - accuracy
  validation_split: 0.2


data:
  test_size: 0.2
  random_state: 42