name: Continuous Integration Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest dvc

      - name: Run tests
        run: pytest -q --disable-warnings || true

      - name: Configure DVC remote
        run: |
          dvc remote modify dagshub --local auth basic
          dvc remote modify dagshub --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify dagshub --local password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Pull data from DVC remote
        run: dvc pull -v

      - name: Run pipeline
        run: dvc repro -v



